# Generated by Django 5.0.6 on 2024-05-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_country_state_city_apiuserprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuserprofile',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='apiuserprofile',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='apiuserprofile',
            name='state_id',
        ),
    ]
